/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Error: typeof import('./components/Utils/Error.vue')['default']
    Film: typeof import('./components/Film.vue')['default']
    FilmDetail: typeof import('./components/FilmDetail.vue')['default']
    FilmDetails: typeof import('./components/Modals/FilmDetails.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Overlay: typeof import('./components/Modals/Overlay.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/Modals/SignIn.vue')['default']
    SignUp: typeof import('./components/Modals/SignUp.vue')['default']
    Spinner: typeof import('./components/Utils/Spinner.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
